name: Build Executables

on:
  push:
    branches:
      - main  # Falls dein Branch 'master' heißt, ändere das hier in 'master'
  workflow_dispatch: # Erlaubt dir, den Build manuell per Button zu starten

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: Quotezzz-Win.exe
          - os: ubuntu-latest
            artifact_name: Quotezzz-Linux
          - os: macos-latest
            artifact_name: Quotezzz-Mac

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller Pillow requests

    - name: Build with PyInstaller
      run: |
        # WICHTIG: Ersetze 'main.py' am Ende der nächsten Zeile, falls dein Skript anders heißt!
        pyinstaller --noconsole --onefile --add-data "background.png${{ matrix.os == 'windows-latest' && ';' || ':' }}." --add-data "star.png${{ matrix.os == 'windows-latest' && ';' || ':' }}." --name "${{ matrix.artifact_name }}" main.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}-bundle
        path: dist/
